default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_bin

development:
  <<: *default
  database: cl_hurryapp_development
  socket: /tmp/mysql.sock
  username: root
  password: kaosbite

test:
  <<: *default
  database: cl_hurryapp_test
  socket: /tmp/mysql.sock
  username: root
  password: kaosbite

production:
  <<: *default
  database: cl_hurryapp_production
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password: hurryapp2016+-