# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590d2e768d316d740937ce5fa48a003434b2ff2f7ba81b6cd322e9291332f1f469b776b5e9cc31846c61dac443a5a48d5f57f4853c7248c3d8b3aed5323eded4

test:
  secret_key_base: bb1aef43aa7f17d24e4d2e7b29e5d112b022deab639c773f6a66c6c471eb8b32b148537e4363b0876364675cacbde3f6a3a0dba2ee66af04718acac6739576c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
